---
title: 3687.us
baseurl: ''
permalink: "/:title/"
palette: yellow
header:
  title: "3687"
  tagline: 3687Tagline
  logo_img: images/logo.png
  bg_img: images/header-bg.jpg
  has_nav: true
  has_social: false
footer:
  content: "&copy; All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
